### ISSUE TITLE
can't run analyzer (possibly python 3.10 issue)

### ISSUE THREAD

**Issue by AddRemover** [SadeghKrmi/5G-Trace-Analyzer#5]
Hi there!
I've installed analyzer via "manual" mode on my ubuntu and whenever I try to load test pcap file provided with the github, I got following error in webserver console
```
Traceback (most recent call last):
  File "/home/user/5G-Trace-Analyzer/fiveGseqAnalyzer/analyzerApp/main.py", line 3, in <module>
    import pyshark
  File "/home/user/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/__init__.py", line 13, in <module>
    from pyshark.capture.live_capture import LiveCapture
  File "/home/user/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/capture/live_capture.py", line 7, in <module>
    from pyshark.capture.capture import Capture
  File "/home/user/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/capture/capture.py", line 14, in <module>
    from pyshark.tshark.output_parser import tshark_xml
  File "/home/user/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/tshark/output_parser/tshark_xml.py", line 2, in <module>
    import lxml.objectify
  File "src/lxml/objectify.pyx", line 1, in init lxml.objectify
ImportError: /home/user/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
Bad Request: /analyzer/ajax/AnalyzeTrace
[14/Jan/2024 13:43:46] "POST /analyzer/ajax/AnalyzeTrace HTTP/1.1" 400 0
```

I believe it's due to python 3.10 was installed.
A side note - please add pcapng support.

**Comment by jes1234Summer** [comment]
Hi @SadeghKrmi, I've installed analyzer via "manual" mode on my ubuntu 24.0.4 LTS and whenever I try to load test pcap file provided with the github, I also get following error in webserver console, due to python 3.10 installed with no pcapng support.

processing file: test_TestRegistration-20250425113750.pcap
Traceback (most recent call last):
  File "/home/wil81520/5G-Trace-Analyzer/fiveGseqAnalyzer/analyzerApp/main.py", line 3, in <module>
    import pyshark
  File "/home/wil81520/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/__init__.py", line 13, in <module>
    from pyshark.capture.live_capture import LiveCapture
  File "/home/wil81520/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/capture/live_capture.py", line 7, in <module>
    from pyshark.capture.capture import Capture
  File "/home/wil81520/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/capture/capture.py", line 14, in <module>
    from pyshark.tshark.output_parser import tshark_xml
  File "/home/wil81520/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/pyshark/tshark/output_parser/tshark_xml.py", line 2, in <module>
    import lxml.objectify
  File "src/lxml/objectify.pyx", line 1, in init lxml.objectify
ImportError: /home/wil81520/5G-Trace-Analyzer/.env/lib/python3.10/site-packages/lxml/etree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
Bad Request: /analyzer/ajax/AnalyzeTrace
[25/Apr/2025 11:37:50] "POST /analyzer/ajax/AnalyzeTrace HTTP/1.1" 400 0
